version: '3.9'
services:
  cloak:
    container_name: Cloak
    build: https://github.com/BrackeysBot/Cloak.git#main
    volumes:
      - type: bind
        source: /var/log/brackeysbot/cloak
        target: /app/logs
      - type: bind
        source: /etc/brackeysbot/cloak
        target: /app/data
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
